### ISSUE TITLE
Path of the found value

### ISSUE THREAD

**Issue by anti-social** [greyblake/jsonpath-rs#19]
I'm writing a converter from json to prometheus metrics format. I have a config that look like:
```yaml
path: $.buffer_pools.*
name: buffer_pool  # |
labels:            # |
- name: type       # |
  value: $1 # <------+ a placeholder for second component from the path that matches the selector above
```

I implemented the feature and if you still support this project I could make a PR.
